// Master list of ALL keyword slugs for internal linking
// This file is auto-generated and used by internal-links-footer component

export const allKeywordSlugs: string[] = [
  // ============ EXISTING 103 KEYWORDS ============
  "skin-doctor-in-vadodara",
  "skin-specialist-in-vadodara",
  "skin-clinic-in-vadodara",
  "best-dermatologist-in-vadodara",
  "dermatologist-in-vadodara",
  "beauty-salon-in-vadodara",
  "skin-care-clinic-in-vadodara",
  "hair-doctor-in-vadodara",
  "best-hair-salon-in-vadodara",
  "best-skin-salon-in-vadodara",
  "hair-clinic-in-vadodara",
  "skin-hospital-in-vadodara",
  "dermatology-clinic-in-vadodara",
  "hair-patch-in-vadodara",
  "hair-specialist-doctor-in-vadodara",
  "acne-treatment-in-vadodara",
  "pimples-treatment-in-vadodara",
  "acne-scar-treatment-in-vadodara",
  "pigmentation-treatment-in-vadodara",
  "melasma-treatment-in-vadodara",
  "dark-spot-removal-in-vadodara",
  "skin-brightening-treatment-in-vadodara",
  "skin-whitening-treatment-in-vadodara",
  "chemical-peel-treatment-in-vadodara",
  "hydrafacial-treatment-in-vadodara",
  "carbon-laser-facial-in-vadodara",
  "chemical-peel-in-vadodara",
  "chemical-face-peel-in-vadodara",
  "skin-peeling-treatment-in-vadodara",
  "laser-skin-treatment-in-vadodara",
  "laser-hair-removal-in-vadodara",
  "laser-acne-scar-treatment-in-vadodara",
  "laser-pigmentation-treatment-in-vadodara",
  "laser-skin-rejuvenation-in-vadodara",
  "tattoo-removal-in-vadodara",
  "anti-aging-treatment-in-vadodara",
  "botox-treatment-in-vadodara",
  "botox-in-vadodara",
  "botox-injection-in-vadodara",
  "botox-hair-treatment-in-vadodara",
  "lip-fillers-in-vadodara",
  "dermal-fillers-in-vadodara",
  "wrinkle-treatment-in-vadodara",
  "fine-lines-treatment-in-vadodara",
  "skin-tightening-treatment-in-vadodara",
  "hair-specialist-in-vadodara",
  "hair-loss-treatment-in-vadodara",
  "hair-fall-treatment-in-vadodara",
  "hair-regrowth-treatment-in-vadodara",
  "hair-growth-treatment-in-vadodara",
  "hair-fall-control-in-vadodara",
  "hair-growth-in-vadodara",
  "hair-treatment-in-vadodara",
  "hair-thinning-treatment-in-vadodara",
  "prp-hair-treatment-in-vadodara",
  "gfc-hair-treatment-in-vadodara",
  "hair-transplant-in-vadodara",
  "fue-hair-transplant-in-vadodara",
  "beard-transplant-in-vadodara",
  "dandruff-treatment-in-vadodara",
  "scalp-treatment-in-vadodara",
  "alopecia-treatment-in-vadodara",
  "vitiligo-treatment-in-vadodara",
  "fungal-skin-infection-treatment-in-vadodara",
  "dark-spots-treatment-in-vadodara",
  "skin-clinic-near-me-in-vadodara",
  "skin-care-clinic-near-me-in-vadodara",
  "skin-and-hair-specialist-in-vadodara",
  "skin-lightening-treatment-in-vadodara",
  "skin-polishing-in-vadodara",
  "skin-tightening-in-vadodara",
  "open-pores-treatment-in-vadodara",
  "stretch-mark-treatment-in-vadodara",
  "tan-removal-treatment-in-vadodara",
  "under-eye-treatment-in-vadodara",
  "lip-enhancement-in-vadodara",
  "double-chin-treatment-in-vadodara",
  "thread-lift-in-vadodara",
  "vampire-facial-in-vadodara",
  "medi-facial-in-vadodara",
  "o3-facial-in-vadodara",
  "hydrafacial-in-vadodara",
  "carbon-peel-in-vadodara",
  "microneedling-in-vadodara",
  "mole-removal-in-vadodara",
  "wart-removal-in-vadodara",
  "skin-tag-removal-in-vadodara",
  "skin-allergy-treatment-in-vadodara",
  "rashes-treatment-in-vadodara",
  "eczema-treatment-in-vadodara",
  "psoriasis-treatment-in-vadodara",
  "fungal-infection-treatment-in-vadodara",
  "cystic-acne-treatment-in-vadodara",
  "hormonal-acne-treatment-in-vadodara",
  "pimple-marks-removal-in-vadodara",
  "cosmetologist-in-vadodara",
  "laser-treatment-for-face-in-vadodara",
  "laser-skin-resurfacing-in-vadodara",
  "glutathione-treatment-in-vadodara",
  "male-pattern-baldness-treatment-in-vadodara",
  "female-hair-loss-treatment-in-vadodara",
  "eyebrow-transplant-in-vadodara",
  "best-hair-doctor-in-vadodara",

  // ============ NEW 370 KEYWORDS ============
  // --- Doctor / Specialist / Clinic (28) ---
  "best-skin-doctor-in-vadodara",
  "best-skin-specialist-in-vadodara",
  "best-skin-clinic-in-vadodara",
  "best-hair-clinic-in-vadodara",
  "best-cosmetologist-in-vadodara",
  "best-skin-care-clinic-in-vadodara",
  "best-dermatology-clinic-in-vadodara",
  "best-skin-hospital-in-vadodara",
  "top-dermatologist-in-vadodara",
  "top-skin-doctor-in-vadodara",
  "top-skin-specialist-in-vadodara",
  "cosmetic-dermatologist-in-vadodara",
  "aesthetic-dermatologist-in-vadodara",
  "aesthetic-clinic-in-vadodara",
  "cosmetic-clinic-in-vadodara",
  "trichologist-in-vadodara",
  "best-trichologist-in-vadodara",
  "skin-and-hair-clinic-in-vadodara",
  "skin-care-specialist-in-vadodara",
  "hair-care-specialist-in-vadodara",
  "pediatric-dermatologist-in-vadodara",
  "lady-dermatologist-in-vadodara",
  "female-dermatologist-in-vadodara",
  "lady-skin-doctor-in-vadodara",
  "female-skin-doctor-in-vadodara",
  "hair-loss-doctor-in-vadodara",
  "hair-loss-clinic-in-vadodara",
  "hair-restoration-clinic-in-vadodara",

  // --- Near Me (10) ---
  "dermatologist-near-me-in-vadodara",
  "skin-doctor-near-me-in-vadodara",
  "hair-clinic-near-me-in-vadodara",
  "hair-doctor-near-me-in-vadodara",
  "skin-specialist-near-me-in-vadodara",
  "hair-specialist-near-me-in-vadodara",
  "hair-transplant-near-me-in-vadodara",
  "laser-hair-removal-near-me-in-vadodara",
  "beauty-salon-near-me-in-vadodara",
  "skin-hospital-near-me-in-vadodara",

  // --- Acne & Pimple (14) ---
  "back-acne-treatment-in-vadodara",
  "body-acne-treatment-in-vadodara",
  "teenage-acne-treatment-in-vadodara",
  "adult-acne-treatment-in-vadodara",
  "acne-specialist-in-vadodara",
  "blackhead-removal-in-vadodara",
  "whitehead-treatment-in-vadodara",
  "acne-marks-treatment-in-vadodara",
  "severe-acne-treatment-in-vadodara",
  "fungal-acne-treatment-in-vadodara",
  "nodular-acne-treatment-in-vadodara",
  "best-acne-treatment-in-vadodara",
  "acne-cure-in-vadodara",
  "comedonal-acne-treatment-in-vadodara",

  // --- Pigmentation & Skin Tone (20) ---
  "hyperpigmentation-treatment-in-vadodara",
  "dark-circle-treatment-in-vadodara",
  "dark-neck-treatment-in-vadodara",
  "skin-discoloration-treatment-in-vadodara",
  "uneven-skin-tone-treatment-in-vadodara",
  "freckles-treatment-in-vadodara",
  "sun-damage-treatment-in-vadodara",
  "age-spot-removal-in-vadodara",
  "dull-skin-treatment-in-vadodara",
  "glowing-skin-treatment-in-vadodara",
  "fairness-treatment-in-vadodara",
  "skin-glow-treatment-in-vadodara",
  "sun-tan-removal-in-vadodara",
  "dark-underarm-treatment-in-vadodara",
  "dark-lip-treatment-in-vadodara",
  "dark-knee-treatment-in-vadodara",
  "dark-elbow-treatment-in-vadodara",
  "dark-inner-thigh-treatment-in-vadodara",
  "depigmentation-treatment-in-vadodara",
  "skin-rejuvenation-in-vadodara",

  // --- Facial Treatments (24) ---
  "facial-treatment-in-vadodara",
  "gold-facial-in-vadodara",
  "diamond-facial-in-vadodara",
  "oxygen-facial-in-vadodara",
  "led-facial-in-vadodara",
  "photo-facial-in-vadodara",
  "brightening-facial-in-vadodara",
  "microdermabrasion-in-vadodara",
  "face-cleanup-in-vadodara",
  "skin-polishing-treatment-in-vadodara",
  "bridal-facial-in-vadodara",
  "anti-aging-facial-in-vadodara",
  "collagen-facial-in-vadodara",
  "charcoal-facial-in-vadodara",
  "dermapen-treatment-in-vadodara",
  "bb-glow-treatment-in-vadodara",
  "glass-skin-treatment-in-vadodara",
  "korean-facial-in-vadodara",
  "aqua-peel-in-vadodara",
  "jet-peel-in-vadodara",
  "glycolic-peel-in-vadodara",
  "salicylic-peel-in-vadodara",
  "tca-peel-in-vadodara",
  "lactic-acid-peel-in-vadodara",

  // --- Laser Treatments (24) ---
  "laser-treatment-in-vadodara",
  "laser-facial-in-vadodara",
  "laser-toning-in-vadodara",
  "co2-laser-treatment-in-vadodara",
  "fractional-laser-treatment-in-vadodara",
  "nd-yag-laser-treatment-in-vadodara",
  "ipl-treatment-in-vadodara",
  "laser-mole-removal-in-vadodara",
  "laser-wart-removal-in-vadodara",
  "laser-skin-tag-removal-in-vadodara",
  "laser-tattoo-removal-in-vadodara",
  "laser-scar-removal-in-vadodara",
  "laser-stretch-mark-removal-in-vadodara",
  "full-body-laser-hair-removal-in-vadodara",
  "face-laser-hair-removal-in-vadodara",
  "underarm-laser-hair-removal-in-vadodara",
  "bikini-laser-hair-removal-in-vadodara",
  "q-switched-laser-in-vadodara",
  "diode-laser-in-vadodara",
  "pico-laser-in-vadodara",
  "permanent-hair-removal-in-vadodara",
  "laser-hair-reduction-in-vadodara",
  "best-laser-hair-removal-in-vadodara",
  "laser-genesis-in-vadodara",

  // --- Anti-Aging, Botox & Fillers (30) ---
  "face-lift-in-vadodara",
  "non-surgical-face-lift-in-vadodara",
  "hifu-treatment-in-vadodara",
  "rf-skin-tightening-in-vadodara",
  "jawline-contouring-in-vadodara",
  "chin-augmentation-in-vadodara",
  "cheek-fillers-in-vadodara",
  "under-eye-fillers-in-vadodara",
  "nasolabial-fold-treatment-in-vadodara",
  "forehead-wrinkle-treatment-in-vadodara",
  "crow-feet-treatment-in-vadodara",
  "laugh-lines-treatment-in-vadodara",
  "neck-wrinkle-treatment-in-vadodara",
  "neck-lift-in-vadodara",
  "collagen-treatment-in-vadodara",
  "anti-aging-clinic-in-vadodara",
  "double-chin-removal-in-vadodara",
  "face-contouring-in-vadodara",
  "v-shape-face-treatment-in-vadodara",
  "face-slimming-treatment-in-vadodara",
  "skin-lifting-treatment-in-vadodara",
  "tear-trough-filler-in-vadodara",
  "nose-filler-in-vadodara",
  "non-surgical-nose-job-in-vadodara",
  "chin-filler-in-vadodara",
  "temple-filler-in-vadodara",
  "face-fat-reduction-in-vadodara",
  "liquid-face-lift-in-vadodara",
  "vampire-face-lift-in-vadodara",
  "hand-rejuvenation-in-vadodara",

  // --- Hair Loss (22) ---
  "baldness-treatment-in-vadodara",
  "receding-hairline-treatment-in-vadodara",
  "premature-greying-treatment-in-vadodara",
  "grey-hair-treatment-in-vadodara",
  "dry-hair-treatment-in-vadodara",
  "hair-breakage-treatment-in-vadodara",
  "frizzy-hair-treatment-in-vadodara",
  "hair-damage-repair-in-vadodara",
  "hair-fall-solution-in-vadodara",
  "hair-volume-treatment-in-vadodara",
  "thin-hair-treatment-in-vadodara",
  "hair-density-treatment-in-vadodara",
  "hair-strengthening-treatment-in-vadodara",
  "postpartum-hair-loss-treatment-in-vadodara",
  "androgenetic-alopecia-treatment-in-vadodara",
  "alopecia-areata-treatment-in-vadodara",
  "telogen-effluvium-treatment-in-vadodara",
  "stress-hair-loss-treatment-in-vadodara",
  "best-hair-fall-treatment-in-vadodara",
  "best-hair-loss-treatment-in-vadodara",
  "best-hair-treatment-in-vadodara",
  "female-pattern-baldness-treatment-in-vadodara",

  // --- Hair Care & Styling (16) ---
  "hair-spa-in-vadodara",
  "keratin-treatment-in-vadodara",
  "hair-smoothening-in-vadodara",
  "hair-rebonding-in-vadodara",
  "hair-straightening-in-vadodara",
  "hair-coloring-in-vadodara",
  "hair-extension-in-vadodara",
  "hair-weaving-in-vadodara",
  "hair-bonding-in-vadodara",
  "hair-replacement-in-vadodara",
  "non-surgical-hair-replacement-in-vadodara",
  "hair-wig-in-vadodara",
  "best-hair-spa-in-vadodara",
  "oily-scalp-treatment-in-vadodara",
  "hair-restoration-in-vadodara",
  "hair-loss-specialist-in-vadodara",

  // --- Hair Transplant Variants (16) ---
  "best-hair-transplant-in-vadodara",
  "dhi-hair-transplant-in-vadodara",
  "bio-fue-hair-transplant-in-vadodara",
  "body-hair-transplant-in-vadodara",
  "female-hair-transplant-in-vadodara",
  "hair-transplant-clinic-in-vadodara",
  "hair-transplant-doctor-in-vadodara",
  "hair-transplant-surgeon-in-vadodara",
  "moustache-transplant-in-vadodara",
  "hair-transplant-specialist-in-vadodara",
  "sapphire-fue-hair-transplant-in-vadodara",
  "robotic-hair-transplant-in-vadodara",
  "unshaven-hair-transplant-in-vadodara",
  "hair-transplant-for-women-in-vadodara",
  "failed-hair-transplant-repair-in-vadodara",
  "sideburn-transplant-in-vadodara",

  // --- Scalp (10) ---
  "scalp-psoriasis-treatment-in-vadodara",
  "scalp-infection-treatment-in-vadodara",
  "itchy-scalp-treatment-in-vadodara",
  "dry-scalp-treatment-in-vadodara",
  "flaky-scalp-treatment-in-vadodara",
  "seborrheic-dermatitis-treatment-in-vadodara",
  "hair-follicle-treatment-in-vadodara",
  "scalp-micropigmentation-in-vadodara",
  "mesotherapy-for-hair-in-vadodara",
  "mesotherapy-in-vadodara",

  // --- PRP/GFC/Regenerative (10) ---
  "prp-for-face-in-vadodara",
  "prp-treatment-in-vadodara",
  "prp-facial-in-vadodara",
  "platelet-rich-plasma-treatment-in-vadodara",
  "stem-cell-therapy-for-hair-in-vadodara",
  "growth-factor-treatment-in-vadodara",
  "exosome-therapy-in-vadodara",
  "exosome-hair-treatment-in-vadodara",
  "prp-for-skin-in-vadodara",
  "prp-injection-for-hair-in-vadodara",

  // --- Skin Conditions (28) ---
  "dermatitis-treatment-in-vadodara",
  "contact-dermatitis-treatment-in-vadodara",
  "atopic-dermatitis-treatment-in-vadodara",
  "urticaria-treatment-in-vadodara",
  "hives-treatment-in-vadodara",
  "lichen-planus-treatment-in-vadodara",
  "rosacea-treatment-in-vadodara",
  "scabies-treatment-in-vadodara",
  "ringworm-treatment-in-vadodara",
  "herpes-treatment-in-vadodara",
  "shingles-treatment-in-vadodara",
  "skin-infection-treatment-in-vadodara",
  "bacterial-skin-infection-treatment-in-vadodara",
  "skin-rash-treatment-in-vadodara",
  "itchy-skin-treatment-in-vadodara",
  "dry-skin-treatment-in-vadodara",
  "oily-skin-treatment-in-vadodara",
  "sensitive-skin-treatment-in-vadodara",
  "molluscum-treatment-in-vadodara",
  "cellulitis-treatment-in-vadodara",
  "folliculitis-treatment-in-vadodara",
  "chronic-urticaria-treatment-in-vadodara",
  "skin-allergy-doctor-in-vadodara",
  "skin-rashes-doctor-in-vadodara",
  "loose-skin-treatment-in-vadodara",
  "saggy-skin-treatment-in-vadodara",
  "dehydrated-skin-treatment-in-vadodara",
  "rough-skin-treatment-in-vadodara",

  // --- Skin Removal (14) ---
  "corn-removal-in-vadodara",
  "callus-removal-in-vadodara",
  "cyst-removal-in-vadodara",
  "lipoma-removal-in-vadodara",
  "sebaceous-cyst-removal-in-vadodara",
  "millia-removal-in-vadodara",
  "xanthelasma-removal-in-vadodara",
  "syringoma-removal-in-vadodara",
  "keratosis-treatment-in-vadodara",
  "skin-growth-removal-in-vadodara",
  "skin-lesion-removal-in-vadodara",
  "fibroma-removal-in-vadodara",
  "verruca-removal-in-vadodara",
  "cherry-angioma-removal-in-vadodara",

  // --- Scar (10) ---
  "scar-removal-in-vadodara",
  "burn-scar-treatment-in-vadodara",
  "surgical-scar-treatment-in-vadodara",
  "chickenpox-scar-treatment-in-vadodara",
  "keloid-treatment-in-vadodara",
  "hypertrophic-scar-treatment-in-vadodara",
  "scar-revision-in-vadodara",
  "ice-pick-scar-treatment-in-vadodara",
  "subcision-treatment-in-vadodara",
  "scar-reduction-treatment-in-vadodara",

  // --- Nail (6) ---
  "nail-fungus-treatment-in-vadodara",
  "nail-disorder-treatment-in-vadodara",
  "ingrown-nail-treatment-in-vadodara",
  "ingrown-toenail-treatment-in-vadodara",
  "nail-psoriasis-treatment-in-vadodara",
  "onychomycosis-treatment-in-vadodara",

  // --- Body (14) ---
  "body-contouring-in-vadodara",
  "fat-reduction-in-vadodara",
  "coolsculpting-in-vadodara",
  "inch-loss-treatment-in-vadodara",
  "cellulite-treatment-in-vadodara",
  "body-polishing-in-vadodara",
  "body-sculpting-in-vadodara",
  "lipolysis-in-vadodara",
  "skin-firming-treatment-in-vadodara",
  "double-chin-removal-in-vadodara",
  "cryolipolysis-in-vadodara",
  "tummy-tightening-in-vadodara",
  "body-skin-tightening-in-vadodara",
  "body-whitening-treatment-in-vadodara",

  // --- Sweat & Misc (4) ---
  "hyperhidrosis-treatment-in-vadodara",
  "excessive-sweating-treatment-in-vadodara",
  "body-odor-treatment-in-vadodara",
  "underarm-whitening-in-vadodara",

  // --- Under Eye (6) ---
  "under-eye-dark-circle-treatment-in-vadodara",
  "eye-bag-treatment-in-vadodara",
  "puffy-eyes-treatment-in-vadodara",
  "under-eye-wrinkle-treatment-in-vadodara",
  "sunken-eyes-treatment-in-vadodara",
  "under-eye-hollowness-treatment-in-vadodara",

  // --- Lip & Cosmetic (6) ---
  "lip-lightening-in-vadodara",
  "lip-pigmentation-treatment-in-vadodara",
  "ear-lobe-repair-in-vadodara",
  "dimple-creation-in-vadodara",
  "skin-texture-treatment-in-vadodara",
  "skin-hydration-treatment-in-vadodara",

  // --- Bridal & Gender-Specific (12) ---
  "bridal-skin-care-in-vadodara",
  "pre-bridal-treatment-in-vadodara",
  "pre-wedding-skin-treatment-in-vadodara",
  "bridal-glow-treatment-in-vadodara",
  "pre-bridal-facial-in-vadodara",
  "groom-facial-in-vadodara",
  "mens-skin-care-in-vadodara",
  "womens-skin-care-in-vadodara",
  "mens-facial-in-vadodara",
  "mens-hair-loss-treatment-in-vadodara",
  "womens-hair-treatment-in-vadodara",
  "mens-hair-treatment-in-vadodara",

  // --- Advanced Technology (10) ---
  "radiofrequency-treatment-in-vadodara",
  "ultherapy-in-vadodara",
  "cryotherapy-in-vadodara",
  "electrocautery-in-vadodara",
  "dermatoscopy-in-vadodara",
  "allergy-test-in-vadodara",
  "patch-test-in-vadodara",
  "skin-biopsy-in-vadodara",
  "skin-screening-in-vadodara",
  "skin-checkup-in-vadodara",

  // --- Intimate Area (4) ---
  "intimate-area-whitening-in-vadodara",
  "bikini-area-whitening-in-vadodara",
  "glutathione-injection-in-vadodara",
  "skin-whitening-injection-in-vadodara",

  // --- Vein / Vascular (4) ---
  "spider-veins-treatment-in-vadodara",
  "varicose-veins-treatment-in-vadodara",
  "broken-capillaries-treatment-in-vadodara",
  "facial-redness-treatment-in-vadodara",

  // --- Cost Pages (28) ---
  "hair-transplant-cost-in-vadodara",
  "fue-hair-transplant-cost-in-vadodara",
  "beard-transplant-cost-in-vadodara",
  "prp-treatment-cost-in-vadodara",
  "gfc-treatment-cost-in-vadodara",
  "laser-hair-removal-cost-in-vadodara",
  "hydrafacial-cost-in-vadodara",
  "chemical-peel-cost-in-vadodara",
  "botox-cost-in-vadodara",
  "dermal-fillers-cost-in-vadodara",
  "thread-lift-cost-in-vadodara",
  "lip-fillers-cost-in-vadodara",
  "acne-treatment-cost-in-vadodara",
  "hair-patch-cost-in-vadodara",
  "skin-whitening-cost-in-vadodara",
  "tattoo-removal-cost-in-vadodara",
  "mole-removal-cost-in-vadodara",
  "skin-tag-removal-cost-in-vadodara",
  "wart-removal-cost-in-vadodara",
  "pigmentation-treatment-cost-in-vadodara",
  "microneedling-cost-in-vadodara",
  "acne-scar-treatment-cost-in-vadodara",
  "hair-fall-treatment-cost-in-vadodara",
  "hair-loss-treatment-cost-in-vadodara",
  "skin-tightening-cost-in-vadodara",
  "hair-spa-cost-in-vadodara",
  "anti-aging-treatment-cost-in-vadodara",
  "facial-treatment-cost-in-vadodara",
];
